# Generated by Django 4.1.7 on 2023-03-29 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_notas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                ("id_usuario", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.TextField(max_length=255)),
            ],
        ),
    ]
