# Generated by Django 4.1.7 on 2023-03-29 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_notas', '0002_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='usuario_nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_notas.nota')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_notas.usuario')),
            ],
        ),
    ]
